In [2]:
import tensorflow as tf
import numpy as np

In [3]:
#张量是具有统一类型（称为 dtype）的多维数组.您可以在 tf.dtypes.DType 中查看所有支持的 dtypes。
#如果您熟悉 NumPy，就会知道张量与 np.arrays 有一定的相似性。
#就像 Python 数值和字符串一样，所有张量都是不可变的：永远无法更新张量的内容，只能创建新的张量。


In [4]:
#下面是一个“标量”（或称“0 秩”张量）。标量包含单个值，但没有“轴”。
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
#“向量”（或称“1 秩”张量）就像一个值列表。向量有 1 个轴：
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [6]:
#“矩阵”（或称“2 秩”张量）有 2 个轴：
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant(
    [[1,2],
    [3,4],
    [5,6]],dtype=tf.float16)

print(rank_2_tensor)



tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [7]:
#张量的轴可能更多，下面是一个包含 3 个轴的张量：
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        ], dtype=tf.int16
)
print(rank_3_tensor)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int16)


In [8]:
#通过使用 np.array 或 tensor.numpy 方法，您可以将张量转换为 NumPy 数组：
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [9]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [27]:
#张量通常包含浮点型和整型数据，但是还有许多其他数据类型，包括：
#复杂的数值
#字符串
#您可以对张量执行基本数学运算，包括加法、逐元素乘法和矩阵乘法。

a = tf.constant([
    [1,2],
    [3,4]
],dtype=tf.int32)

b = tf.constant([
    [5,6],
    [7,8]
],dtype=tf.int32)


print(tf.add(a,b),"\n")
print(tf.subtract(a,b),"\n")
print(tf.multiply(a,b),"\n")
print(tf.divide(a,b),"\n")
print(tf.matmul(a,b),"\n")


tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32) 



In [45]:
#各种运算都可以使用张量。
#tf.reduce_max 是 TensorFlow 中的一个函数，用于计算张量（tensor）中的最大值。它可以沿着张量的一个或多个维度进行操作。
a = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10]
],dtype=tf.float32)

# Find the largest value
print(tf.reduce_max(a),"\n") #全局最大值
print(tf.reduce_max(a,axis=1),"\n") #1轴/行最大值
print(tf.reduce_max(a,axis=0),"\n") #0轴/列最大值

# Find the index of the largest value
print(tf.math.argmax(a,0),"\n") #每列最大值索引
print(tf.math.argmax(a,1),"\n") #行最大值索引

# Compute the softmax
#tf.nn.softmax 函数用于计算张量中每个元素的 softmax 激活值。
#Softmax 函数将输入的张量转换为一个新的张量，其中每个元素的取值范围在 0 到 1 之间，并且所有元素之和为 1。这使得 softmax 激活函数特别适合用于多分类问题中的输出层，其中每个输出节点表示一个类别的概率。
print(tf.nn.softmax(a))

tf.Tensor(10.0, shape=(), dtype=float32) 

tf.Tensor([ 5. 10.], shape=(2,), dtype=float32) 

tf.Tensor([ 6.  7.  8.  9. 10.], shape=(5,), dtype=float32) 

tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int64) 

tf.Tensor([4 4], shape=(2,), dtype=int64) 

tf.Tensor(
[[0.01165623 0.03168492 0.08612853 0.23412165 0.63640857]
 [0.01165623 0.03168492 0.08612853 0.23412165 0.63640857]], shape=(2, 5), dtype=float32)


In [48]:
##张量有形状。下面是几个相关术语：

#形状：张量的每个轴的长度（元素数量）。
#秩：张量轴数。标量的秩为 0，向量的秩为 1，矩阵的秩为 2。
#轴或维度：张量的一个特殊维度。
#大小：张量的总项数，即形状矢量元素的乘积
#注：虽然您可能会看到“二维张量”之类的表述，但 2 秩张量通常并不是用来描述二维空间。

rank_4_tensor = tf.zeros([3,2,4,5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [52]:
#但请注意，Tensor.ndim 和 Tensor.shape 特性不返回 Tensor 对象。如果您需要 Tensor，请使用 tf.rank 或 tf.shape 函数。这种差异不易察觉，但在构建计算图时（稍后）可能非常重要。
print(tf.rank(rank_4_tensor),'\n')
print(tf.shape(rank_4_tensor),'\n')

tf.Tensor(4, shape=(), dtype=int32) 

tf.Tensor([3 2 4 5], shape=(4,), dtype=int32) 



In [ ]:
#虽然通常用索引来指代轴，但是您始终要记住每个轴的含义。轴一般按照从全局到局部的顺序进行排序：首先是批次轴，随后是空间维度，最后是每个位置的特征。这样，在内存中，特征向量就会位于连续的区域。
# https://tensorflow.google.cn/guide/tensor?hl=zh-cn   结合2个图理解
# 3 2 4 5
# 3 - Batch
# 2 - Height
# 4 - Width
# 5 - Features