In [2]:
import tensorflow as tf
import numpy as np

In [5]:
#张量是具有统一类型（称为 dtype）的多维数组.您可以在 tf.dtypes.DType 中查看所有支持的 dtypes。
#如果您熟悉 NumPy，就会知道张量与 np.arrays 有一定的相似性。
#就像 Python 数值和字符串一样，所有张量都是不可变的：永远无法更新张量的内容，只能创建新的张量。


In [7]:
#下面是一个“标量”（或称“0 秩”张量）。标量包含单个值，但没有“轴”。
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
#“向量”（或称“1 秩”张量）就像一个值列表。向量有 1 个轴：
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [9]:
#“矩阵”（或称“2 秩”张量）有 2 个轴：
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant(
    [[1,2],
    [3,4],
    [5,6]],dtype=tf.float16)

print(rank_2_tensor)



tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [10]:
#张量的轴可能更多，下面是一个包含 3 个轴的张量：
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        ], dtype=tf.int16
)
print(rank_3_tensor)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int16)
